language: node_js
node_js:
  - "6.9"
  - "6.8"
  - "6.7"
  - "6.6"
  - "6.5"
  - "6.4"
  - "6.3"
  - "6.2"
  - "6.1"
  - "6.0"
  - "4.6"
  - "4.5"
  - "4.4"
  - "4.3"
  - "4.2"
  - "4.1"
  - "4.0"

install:
  - npm install

before_script:
  - npm run travis-test-server &

script:
  - sleep 1
  - npm test
